<?php

namespace App\Imports;

use Maatwebsite\Excel\Concerns\WithMultipleSheets;

class MultiSheetSoImport implements WithMultipleSheets
{
    public function sheets(): array
    {
        return [
            'DIPLOMA IN AGRITECH'       => new SoMasterListImport('Diploma in Agriculture Technology'),
            'BAT'                      => new SoMasterListImport('Bachelor in Agricultural Technology'),
            'BSAIS'                    => new SoMasterListImport('Bachelor of Science in Accounting Information Systems'),
            'BS ACC'                   => new SoMasterListImport('Bachelor of Science in Accounting'),
            'BSIA'                     => new SoMasterListImport('Bachelor of Science in Internal Auditing'),
            'BS AGRICULTURE'           => new SoMasterListImport('Bachelor of Science in Agriculture'),
            'BACH OF SECURITY MNGT.'   => new SoMasterListImport('Bachelor of Arts in Security Management'),
            'BSC'                      => new SoMasterListImport('Bachelor of Science in Commerce'),
            'BSBA'                     => new SoMasterListImport('Bachelor of Science in Business Administration'),
            'BS CUSTOMS ADM.'          => new SoMasterListImport('Bachelor of Science in Customs Administration'),
            'BS ENTREPRENEURSHIP'      => new SoMasterListImport('Bachelor of Science in Entrepreneurship'),
            'ASSO.COMP.TECH'           => new SoMasterListImport('Associate in Computer Technology'),
            'BS COM. SCIE.'            => new SoMasterListImport('Bachelor of Science in Communication Sciences'),
            'BSIT'                     => new SoMasterListImport('Bachelor of Science in Information Technology'),
            'BS CIVIL ENG.'            => new SoMasterListImport('Bachelor of Science in Civil Engineering'),
            'BS COM ENG'               => new SoMasterListImport('Bachelor of Science in Computer Engineering'),
            'BSEE'                     => new SoMasterListImport('Bachelor of Science in Electrical Engineering'),
            'BS GEODETIC ENG'          => new SoMasterListImport('Bachelor of Science in Geodetic Engineering'),
            'BS ECE'                   => new SoMasterListImport('Bachelor of Science in Electronics and Communications Engineering'),
            'BS MECHANICAL ENG'        => new SoMasterListImport('Bachelor of Science in Mechanical Engineering'),
            'BACHELOR OF SPECIAL EDUCATION' => new SoMasterListImport('Bachelor of Special Education'),
            'BSED'                     => new SoMasterListImport('Bachelor of Secondary Education'),
            'ASSO. IN HRM'             => new SoMasterListImport('Associate in Hotel and Restaurant Management'),
            'BEED'                     => new SoMasterListImport('Bachelor of Elementary Education'),
            'BS PHYSICAL EDUC.'        => new SoMasterListImport('Bachelor of Science in Physical Education'),
            'BS IN EARLY CHILDHOOD EDUCATION' => new SoMasterListImport('Bachelor of Science in Early Childhood Education'),
            'BS CRIM'                  => new SoMasterListImport('Bachelor of Science in Criminology'),
            'BS AGRI BUSINESS'         => new SoMasterListImport('Bachelor of Science in Agricultural Business'),
            'BSTM'                     => new SoMasterListImport('Bachelor of Science in Tourism Management'),
            'BS HRMBSHM'               => new SoMasterListImport('Bachelor of Science in Hospitality and Restaurant Management'),
            'BS INFOR. SYSTEM'         => new SoMasterListImport('Bachelor of Science in Information Systems'),
            'BSMA'                     => new SoMasterListImport('Bachelor of Science in Maritime Administration'),
            'BS MARINE TRANS.'         => new SoMasterListImport('Bachelor of Science in Marine Transportation'),
            'ASS. IN OFFICE ADMINISTRATION' => new SoMasterListImport('Associate in Office Administration'),
            'BS MARINE ENG.'           => new SoMasterListImport('Bachelor of Science in Marine Engineering'),
            'BS MED TECH'              => new SoMasterListImport('Bachelor of Science in Medical Technology'),
            'BS RAD. TECH'             => new SoMasterListImport('Bachelor of Science in Radiologic Technology'),
            'BS PHARMACY'              => new SoMasterListImport('Bachelor of Science in Pharmacy'),
            'BS NURSING'               => new SoMasterListImport('Bachelor of Science in Nursing'),
            '2YRS MIDWIFERY'           => new SoMasterListImport('Two-Year Midwifery Program'),
            'BS MIDWIFERY'             => new SoMasterListImport('Bachelor of Science in Midwifery'),
            'BS PHYSICAL THERAPY'      => new SoMasterListImport('Bachelor of Science in Physical Therapy'),
            'BS RESPI. THERAPY'        => new SoMasterListImport('Bachelor of Science in Respiratory Therapy'),
            'BS Mass Com'              => new SoMasterListImport('Bachelor of Science in Mass Communication'),
            'ASSO. RAD TECH'           => new SoMasterListImport('Associate in Radiologic Technology'),
            'BS OFFICE ADMINISTRATION' => new SoMasterListImport('Bachelor of Science in Office Administration'),
            'BS POLICE ADMIN.'         => new SoMasterListImport('Bachelor of Science in Police Administration'),
            'BS REM'                   => new SoMasterListImport('Bachelor of Science in Real Estate Management'),
            'BS SOCIAL WORK'           => new SoMasterListImport('Bachelor of Science in Social Work'),
            'BTTEBTVTED'               => new SoMasterListImport('Bachelor of Technical and Technology Education'),
            'BTLED'                    => new SoMasterListImport('Bachelor of Technical and Livelihood Education'),
            'MASTER OF SCIENCE IN CRIMINAL J' => new SoMasterListImport('Master of Science in Criminal Justice'),
            'MLIS'                     => new SoMasterListImport('Master of Library and Information Science'),
            'MAED'                     => new SoMasterListImport('Master of Arts in Education'),
            'MASTER OF ARTS'           => new SoMasterListImport('Master of Arts'),
            'BS BIOLOGY'               => new SoMasterListImport('Bachelor of Science in Biology'),
            'MBA'                      => new SoMasterListImport('Master of Business Administration'),
            'MPA'                      => new SoMasterListImport('Master of Public Administration'),
            'MPM'                      => new SoMasterListImport('Master of Public Management'),
            'Ed.D'                     => new SoMasterListImport('Doctor of Education'),
            'Ph.D'                     => new SoMasterListImport('Doctor of Philosophy'),
            'DOCTOR OF MEDICINE'       => new SoMasterListImport('Doctor of Medicine'),
            'BACHELOR OF ARTS'         => new SoMasterListImport('Bachelor of Arts'),
            'BS ACC TECH'              => new SoMasterListImport('Bachelor of Science in Accounting Technology'),
            'BLIS'                     => new SoMasterListImport('Bachelor of Library and Information Science'),
        ];
    }
}
